version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/react
hooks:
  # ApplicationStop:
  #   - location: Scripts/stop_node
  #     timeout: 500
  #     runas: root
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: Scripts/after_install.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: Scripts/start_node_Dev.sh
      timeout: 500
      runas: root